---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenheng.
--- DateTime: 24-10-26 下午5:02
---

local SvrComm = require("whmod.SvrComm")
local db = require("mydb")
local whmod = require("whmod")

local g_svrid

function OnServerMsg(source, ...)
    local datas = {...}
    print("登陆服务 接收到其他服务的数据： source = ", source, ", data = ", datas[1] or "nil")
end

whmod.start(function(svrid, ...)
    g_svrid = svrid
    print("登陆服务启动!!!  svrid ---> " .. svrid)

    local gateway_id = SvrComm.getSvrid("gateway1");

    SvrComm.send(svrid, gateway_id, "test", "hey", "fuck you", 2233, {name = "xwz", sex = 1})

    local ret = db.select("select * from user")
end , ...)