---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenheng.
--- DateTime: 24-10-26 下午4:08
---

local net_comm = {}

--网络数据类型
NET_TYPE = {
    ACCEPT = 1, --监听
    DATA = 2,   --读数据
    CLOSE = 3,  --关闭
}

local net_func_tb = {}

function net_comm.NewService(type, config_id)
    return sunnet.NewService(type, config_id or 0)
end

function net_comm.listen(svrid, port, ip)
    if type(port) ~= "number" then
        print("please enter a number port...")
        return
    end
    sunnet.Listen(svrid, port, ip)
    print(string.format("服务id = %s ---> 开启监听端口: %s", svrid, port))
end

function net_comm.register(net_type, func)
    if net_func_tb[net_type] then
        print("net_comm.register the net_type is exist: " .. net_type)
        return
    end

    if type(func) ~= "function" then
        print("net_comm.register not a function...")
        return
    end

    net_func_tb[net_type] = func
end

function net_comm.dispatcher(net_type, ...)
    local func = net_func_tb[net_type]

    if not func then
        print("net_comm.dispatcher: net_type is error: " .. net_type)
        return
    end

    func(...)
end

_G.net_dispatcher = net_comm.dispatcher

return net_comm