---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenheng.
--- DateTime: 24-10-26 下午5:21
---

local server_comm = {}

--记录服务数据 key是服务名，值是服务id

function server_comm.register(name, svrid)
    if type(name) ~= "string" then
        print("server_comm.register | name error")
        return
    end

    if type(svrid) ~= "number" then
        print("server_comm.register | svrrid error")
    end

    sunnet.RegisterSvr(name, svrid)

    print(string.format("注册成功: name = %s, svrid = %s", name, svrid))
end

function server_comm.getSvrid(name)
    if type(name) ~= "string" then
        print("the svrname is error " .. (name or "nil"))
        return -1
    end
    local svrid = sunnet.GetSvrId(name)

    print(string.format("get the svr name(%s) ----> id = %s", name, svrid))
    return svrid
end

function server_comm.send(source, to, ...)
    local serverMsgMod = sunnet["serverMsgMod"]
    if not serverMsgMod then
        print("server_comm.send | serverMsgMod is null")
        return
    end
    local args = {...}
    print(string.format("开始下方服务间数据: 额外参数数量 = %s", #args))
    serverMsgMod[to] = {
        args = ...,
        from = source,
    }

    sunnet.Send(source, to, "test", ...)
end

function ServerMsgCallBack(source, to, buff)
    local serverMsgMod = sunnet.serverMsgMod
    if not serverMsgMod then
        print("server_comm.send | serverMsgMod is null")
        return
    end


end


return server_comm