// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecmd.proto

#include "basecmd.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR netHeadCmd::netHeadCmd(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0u
  , /*decltype(_impl_.subtype_)*/0u
  , /*decltype(_impl_.len_)*/0u
  , /*decltype(_impl_.version_)*/0u
  , /*decltype(_impl_.checkcode_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct netHeadCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR netHeadCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~netHeadCmdDefaultTypeInternal() {}
  union {
    netHeadCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 netHeadCmdDefaultTypeInternal _netHeadCmd_default_instance_;
static ::_pb::Metadata file_level_metadata_basecmd_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_basecmd_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_basecmd_2eproto = nullptr;

const uint32_t TableStruct_basecmd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _impl_.subtype_),
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _impl_.len_),
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _impl_.version_),
  PROTOBUF_FIELD_OFFSET(::netHeadCmd, _impl_.checkcode_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::netHeadCmd)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_netHeadCmd_default_instance_._instance,
};

const char descriptor_table_protodef_basecmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rbasecmd.proto\"\\\n\nnetHeadCmd\022\014\n\004type\030\001 "
  "\001(\r\022\017\n\007subtype\030\002 \001(\r\022\013\n\003len\030\003 \001(\r\022\017\n\007ver"
  "sion\030\004 \001(\r\022\021\n\tcheckcode\030\005 \001(\rb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_basecmd_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_basecmd_2eproto = {
    false, false, 117, descriptor_table_protodef_basecmd_2eproto,
    "basecmd.proto",
    &descriptor_table_basecmd_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_basecmd_2eproto::offsets,
    file_level_metadata_basecmd_2eproto, file_level_enum_descriptors_basecmd_2eproto,
    file_level_service_descriptors_basecmd_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_basecmd_2eproto_getter() {
  return &descriptor_table_basecmd_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_basecmd_2eproto(&descriptor_table_basecmd_2eproto);

// ===================================================================

class netHeadCmd::_Internal {
 public:
};

netHeadCmd::netHeadCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:netHeadCmd)
}
netHeadCmd::netHeadCmd(const netHeadCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  netHeadCmd* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.subtype_){}
    , decltype(_impl_.len_){}
    , decltype(_impl_.version_){}
    , decltype(_impl_.checkcode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.checkcode_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.checkcode_));
  // @@protoc_insertion_point(copy_constructor:netHeadCmd)
}

inline void netHeadCmd::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0u}
    , decltype(_impl_.subtype_){0u}
    , decltype(_impl_.len_){0u}
    , decltype(_impl_.version_){0u}
    , decltype(_impl_.checkcode_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

netHeadCmd::~netHeadCmd() {
  // @@protoc_insertion_point(destructor:netHeadCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void netHeadCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void netHeadCmd::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void netHeadCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:netHeadCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.checkcode_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.checkcode_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* netHeadCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 subtype = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.subtype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 len = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.len_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 checkcode = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.checkcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* netHeadCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:netHeadCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_type(), target);
  }

  // uint32 subtype = 2;
  if (this->_internal_subtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_subtype(), target);
  }

  // uint32 len = 3;
  if (this->_internal_len() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_len(), target);
  }

  // uint32 version = 4;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_version(), target);
  }

  // uint32 checkcode = 5;
  if (this->_internal_checkcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_checkcode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:netHeadCmd)
  return target;
}

size_t netHeadCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:netHeadCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_type());
  }

  // uint32 subtype = 2;
  if (this->_internal_subtype() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_subtype());
  }

  // uint32 len = 3;
  if (this->_internal_len() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_len());
  }

  // uint32 version = 4;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_version());
  }

  // uint32 checkcode = 5;
  if (this->_internal_checkcode() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_checkcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData netHeadCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    netHeadCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*netHeadCmd::GetClassData() const { return &_class_data_; }


void netHeadCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<netHeadCmd*>(&to_msg);
  auto& from = static_cast<const netHeadCmd&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netHeadCmd)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_subtype() != 0) {
    _this->_internal_set_subtype(from._internal_subtype());
  }
  if (from._internal_len() != 0) {
    _this->_internal_set_len(from._internal_len());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  if (from._internal_checkcode() != 0) {
    _this->_internal_set_checkcode(from._internal_checkcode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void netHeadCmd::CopyFrom(const netHeadCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netHeadCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool netHeadCmd::IsInitialized() const {
  return true;
}

void netHeadCmd::InternalSwap(netHeadCmd* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(netHeadCmd, _impl_.checkcode_)
      + sizeof(netHeadCmd::_impl_.checkcode_)
      - PROTOBUF_FIELD_OFFSET(netHeadCmd, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata netHeadCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_basecmd_2eproto_getter, &descriptor_table_basecmd_2eproto_once,
      file_level_metadata_basecmd_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::netHeadCmd*
Arena::CreateMaybeMessage< ::netHeadCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::netHeadCmd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
