// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecmd.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_basecmd_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_basecmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_basecmd_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_basecmd_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_basecmd_2eproto;
class netHeadCmd;
struct netHeadCmdDefaultTypeInternal;
extern netHeadCmdDefaultTypeInternal _netHeadCmd_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::netHeadCmd* Arena::CreateMaybeMessage<::netHeadCmd>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class netHeadCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:netHeadCmd) */ {
 public:
  inline netHeadCmd() : netHeadCmd(nullptr) {}
  ~netHeadCmd() override;
  explicit PROTOBUF_CONSTEXPR netHeadCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  netHeadCmd(const netHeadCmd& from);
  netHeadCmd(netHeadCmd&& from) noexcept
    : netHeadCmd() {
    *this = ::std::move(from);
  }

  inline netHeadCmd& operator=(const netHeadCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline netHeadCmd& operator=(netHeadCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const netHeadCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const netHeadCmd* internal_default_instance() {
    return reinterpret_cast<const netHeadCmd*>(
               &_netHeadCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(netHeadCmd& a, netHeadCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(netHeadCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(netHeadCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  netHeadCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<netHeadCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const netHeadCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const netHeadCmd& from) {
    netHeadCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(netHeadCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "netHeadCmd";
  }
  protected:
  explicit netHeadCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kSubtypeFieldNumber = 2,
    kLenFieldNumber = 3,
    kVersionFieldNumber = 4,
    kCheckcodeFieldNumber = 5,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // uint32 subtype = 2;
  void clear_subtype();
  uint32_t subtype() const;
  void set_subtype(uint32_t value);
  private:
  uint32_t _internal_subtype() const;
  void _internal_set_subtype(uint32_t value);
  public:

  // uint32 len = 3;
  void clear_len();
  uint32_t len() const;
  void set_len(uint32_t value);
  private:
  uint32_t _internal_len() const;
  void _internal_set_len(uint32_t value);
  public:

  // uint32 version = 4;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // uint32 checkcode = 5;
  void clear_checkcode();
  uint32_t checkcode() const;
  void set_checkcode(uint32_t value);
  private:
  uint32_t _internal_checkcode() const;
  void _internal_set_checkcode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:netHeadCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t type_;
    uint32_t subtype_;
    uint32_t len_;
    uint32_t version_;
    uint32_t checkcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_basecmd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// netHeadCmd

// uint32 type = 1;
inline void netHeadCmd::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t netHeadCmd::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t netHeadCmd::type() const {
  // @@protoc_insertion_point(field_get:netHeadCmd.type)
  return _internal_type();
}
inline void netHeadCmd::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void netHeadCmd::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:netHeadCmd.type)
}

// uint32 subtype = 2;
inline void netHeadCmd::clear_subtype() {
  _impl_.subtype_ = 0u;
}
inline uint32_t netHeadCmd::_internal_subtype() const {
  return _impl_.subtype_;
}
inline uint32_t netHeadCmd::subtype() const {
  // @@protoc_insertion_point(field_get:netHeadCmd.subtype)
  return _internal_subtype();
}
inline void netHeadCmd::_internal_set_subtype(uint32_t value) {
  
  _impl_.subtype_ = value;
}
inline void netHeadCmd::set_subtype(uint32_t value) {
  _internal_set_subtype(value);
  // @@protoc_insertion_point(field_set:netHeadCmd.subtype)
}

// uint32 len = 3;
inline void netHeadCmd::clear_len() {
  _impl_.len_ = 0u;
}
inline uint32_t netHeadCmd::_internal_len() const {
  return _impl_.len_;
}
inline uint32_t netHeadCmd::len() const {
  // @@protoc_insertion_point(field_get:netHeadCmd.len)
  return _internal_len();
}
inline void netHeadCmd::_internal_set_len(uint32_t value) {
  
  _impl_.len_ = value;
}
inline void netHeadCmd::set_len(uint32_t value) {
  _internal_set_len(value);
  // @@protoc_insertion_point(field_set:netHeadCmd.len)
}

// uint32 version = 4;
inline void netHeadCmd::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t netHeadCmd::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t netHeadCmd::version() const {
  // @@protoc_insertion_point(field_get:netHeadCmd.version)
  return _internal_version();
}
inline void netHeadCmd::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void netHeadCmd::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:netHeadCmd.version)
}

// uint32 checkcode = 5;
inline void netHeadCmd::clear_checkcode() {
  _impl_.checkcode_ = 0u;
}
inline uint32_t netHeadCmd::_internal_checkcode() const {
  return _impl_.checkcode_;
}
inline uint32_t netHeadCmd::checkcode() const {
  // @@protoc_insertion_point(field_get:netHeadCmd.checkcode)
  return _internal_checkcode();
}
inline void netHeadCmd::_internal_set_checkcode(uint32_t value) {
  
  _impl_.checkcode_ = value;
}
inline void netHeadCmd::set_checkcode(uint32_t value) {
  _internal_set_checkcode(value);
  // @@protoc_insertion_point(field_set:netHeadCmd.checkcode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_basecmd_2eproto
