// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectionCmd.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ConnectionCmd_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ConnectionCmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ConnectionCmd_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ConnectionCmd_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ConnectionCmd_2eproto;
namespace Connection {
class ConnectionReqCmd;
struct ConnectionReqCmdDefaultTypeInternal;
extern ConnectionReqCmdDefaultTypeInternal _ConnectionReqCmd_default_instance_;
}  // namespace Connection
PROTOBUF_NAMESPACE_OPEN
template<> ::Connection::ConnectionReqCmd* Arena::CreateMaybeMessage<::Connection::ConnectionReqCmd>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Connection {

// ===================================================================

class ConnectionReqCmd final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Connection.ConnectionReqCmd) */ {
 public:
  inline ConnectionReqCmd() : ConnectionReqCmd(nullptr) {}
  ~ConnectionReqCmd() override;
  explicit PROTOBUF_CONSTEXPR ConnectionReqCmd(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConnectionReqCmd(const ConnectionReqCmd& from);
  ConnectionReqCmd(ConnectionReqCmd&& from) noexcept
    : ConnectionReqCmd() {
    *this = ::std::move(from);
  }

  inline ConnectionReqCmd& operator=(const ConnectionReqCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnectionReqCmd& operator=(ConnectionReqCmd&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConnectionReqCmd& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConnectionReqCmd* internal_default_instance() {
    return reinterpret_cast<const ConnectionReqCmd*>(
               &_ConnectionReqCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConnectionReqCmd& a, ConnectionReqCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(ConnectionReqCmd* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnectionReqCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConnectionReqCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConnectionReqCmd>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConnectionReqCmd& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConnectionReqCmd& from) {
    ConnectionReqCmd::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectionReqCmd* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Connection.ConnectionReqCmd";
  }
  protected:
  explicit ConnectionReqCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMAccountFieldNumber = 1,
    kMPasswdFieldNumber = 2,
  };
  // string m_account = 1;
  void clear_m_account();
  const std::string& m_account() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_account(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_account();
  PROTOBUF_NODISCARD std::string* release_m_account();
  void set_allocated_m_account(std::string* m_account);
  private:
  const std::string& _internal_m_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_account(const std::string& value);
  std::string* _internal_mutable_m_account();
  public:

  // string m_passwd = 2;
  void clear_m_passwd();
  const std::string& m_passwd() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_passwd(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_passwd();
  PROTOBUF_NODISCARD std::string* release_m_passwd();
  void set_allocated_m_passwd(std::string* m_passwd);
  private:
  const std::string& _internal_m_passwd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_passwd(const std::string& value);
  std::string* _internal_mutable_m_passwd();
  public:

  // @@protoc_insertion_point(class_scope:Connection.ConnectionReqCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_account_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_passwd_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ConnectionCmd_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectionReqCmd

// string m_account = 1;
inline void ConnectionReqCmd::clear_m_account() {
  _impl_.m_account_.ClearToEmpty();
}
inline const std::string& ConnectionReqCmd::m_account() const {
  // @@protoc_insertion_point(field_get:Connection.ConnectionReqCmd.m_account)
  return _internal_m_account();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConnectionReqCmd::set_m_account(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_account_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Connection.ConnectionReqCmd.m_account)
}
inline std::string* ConnectionReqCmd::mutable_m_account() {
  std::string* _s = _internal_mutable_m_account();
  // @@protoc_insertion_point(field_mutable:Connection.ConnectionReqCmd.m_account)
  return _s;
}
inline const std::string& ConnectionReqCmd::_internal_m_account() const {
  return _impl_.m_account_.Get();
}
inline void ConnectionReqCmd::_internal_set_m_account(const std::string& value) {
  
  _impl_.m_account_.Set(value, GetArenaForAllocation());
}
inline std::string* ConnectionReqCmd::_internal_mutable_m_account() {
  
  return _impl_.m_account_.Mutable(GetArenaForAllocation());
}
inline std::string* ConnectionReqCmd::release_m_account() {
  // @@protoc_insertion_point(field_release:Connection.ConnectionReqCmd.m_account)
  return _impl_.m_account_.Release();
}
inline void ConnectionReqCmd::set_allocated_m_account(std::string* m_account) {
  if (m_account != nullptr) {
    
  } else {
    
  }
  _impl_.m_account_.SetAllocated(m_account, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_account_.IsDefault()) {
    _impl_.m_account_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Connection.ConnectionReqCmd.m_account)
}

// string m_passwd = 2;
inline void ConnectionReqCmd::clear_m_passwd() {
  _impl_.m_passwd_.ClearToEmpty();
}
inline const std::string& ConnectionReqCmd::m_passwd() const {
  // @@protoc_insertion_point(field_get:Connection.ConnectionReqCmd.m_passwd)
  return _internal_m_passwd();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConnectionReqCmd::set_m_passwd(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_passwd_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Connection.ConnectionReqCmd.m_passwd)
}
inline std::string* ConnectionReqCmd::mutable_m_passwd() {
  std::string* _s = _internal_mutable_m_passwd();
  // @@protoc_insertion_point(field_mutable:Connection.ConnectionReqCmd.m_passwd)
  return _s;
}
inline const std::string& ConnectionReqCmd::_internal_m_passwd() const {
  return _impl_.m_passwd_.Get();
}
inline void ConnectionReqCmd::_internal_set_m_passwd(const std::string& value) {
  
  _impl_.m_passwd_.Set(value, GetArenaForAllocation());
}
inline std::string* ConnectionReqCmd::_internal_mutable_m_passwd() {
  
  return _impl_.m_passwd_.Mutable(GetArenaForAllocation());
}
inline std::string* ConnectionReqCmd::release_m_passwd() {
  // @@protoc_insertion_point(field_release:Connection.ConnectionReqCmd.m_passwd)
  return _impl_.m_passwd_.Release();
}
inline void ConnectionReqCmd::set_allocated_m_passwd(std::string* m_passwd) {
  if (m_passwd != nullptr) {
    
  } else {
    
  }
  _impl_.m_passwd_.SetAllocated(m_passwd, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_passwd_.IsDefault()) {
    _impl_.m_passwd_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Connection.ConnectionReqCmd.m_passwd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Connection

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ConnectionCmd_2eproto
