---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenheng.
--- DateTime: 23-4-24 上午12:17
---
package.path = package.path .. ";/home/wenheng/Desktop/workspace/CppExcise/boostExcise/boost_asio_new/luaScript/userglobal.lua"

require("userglobal")

function main()
    local date = os.date("*t")
    local datetime = string.format("%04d-%02d-%2d %02d:%02d:%02d", date.year, date.month, date.day, date.hour, date.min, date.sec)
    print(string.format("%s>main load: %s", string.rep("-", 10), datetime))

end

main()

local function writeToFile()

end

function lua_writeFile(netMsg)
    if not netMsg then 
        print("netMsg is empty")
        return 
    end
    local head = netMsg.head
    --print(string.format("name = %s, ip = %s", head.info.name, head.info.ip))
    --print("netMsg's body = ", netMsg.body)
    local tb = {}
    tb.ip = head.info.ip
    tb.name = head.info.name
    tb.type = head.type
    tb.len = head.len
    tb.version = head.version
    tb.checknum = head.checknum
    tb.body = netMsg.body

    local str = string.serialize(tb)
    --print("序列化字符串: ", str)

    local _, date, datetime = GetDate()
    --print("date, datetime = ", date, datetime)
    --print("filepath = ", LOGFILEPATH .. date .. ".log")
    local fd = OpenFile(LOGFILEPATH .. date .. ".log", "a+")
    local content = fd:read("*a")
    --print("content = ", content)

    local str2tb = string.unserialize(content)
    --print("type(str2tb) = ", type(str2tb))
    str2tb[datetime] = tb

    dump(str2tb)

    fd:close()

    --print("打印序列化后的表： ", string.serialize(str2tb))
    fd = OpenFile(LOGFILEPATH .. date .. ".log", "w")
    fd:write(string.serialize(str2tb))
    fd:close()
    print("fd wirte done")
end

function test_getuserdata(netPtr)
    print("type(netPtr) = ", type(netPtr))
    print(string.format("type = %d, len = %d, version = %d, checknum = %d", netPtr.type, netPtr.len, netPtr.version
        , netPtr.checknum))

    print("type(netPtr.info) = ", type(netPtr.info))
    print(netPtr.info.name, netPtr.info.ip)
end

function lua_loadNetMsg()
    local tb = {}
    local _, date, datetime = GetDate()
    local fd = OpenFile(LOGFILEPATH .. date .. ".log", "a+")
    local content = fd:read("*a")

    tb = string.unserialize(content)

    print("打印读取的聊天数据:")
    dump(tb)

    local array = {}
    for _, v in pairs(tb) do
        array[#array+1] = v
    end

    return array
end