---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenheng.
--- DateTime: 24-11-30 下午5:10
---

ServerConfig = {
    gateway = {
        [1] = {
            id = 1,
            ip = "127.0.0.1",
            port = 8000,
        },
        [2] = {
            id = 2,
            ip = "127.0.0.1",
            port = 8001,
        }
    },

}